/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DooboxRouteImport } from './routes/doobox'
import { Route as DooRouteImport } from './routes/doo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DooIndexRouteImport } from './routes/doo/index'
import { Route as DooIdRouteImport } from './routes/doo/$id'

const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DooboxRoute = DooboxRouteImport.update({
  id: '/doobox',
  path: '/doobox',
  getParentRoute: () => rootRouteImport,
} as any)
const DooRoute = DooRouteImport.update({
  id: '/doo',
  path: '/doo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DooIndexRoute = DooIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DooRoute,
} as any)
const DooIdRoute = DooIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DooRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/doo': typeof DooRouteWithChildren
  '/doobox': typeof DooboxRoute
  '/login': typeof LoginRoute
  '/requests': typeof RequestsRoute
  '/doo/$id': typeof DooIdRoute
  '/doo/': typeof DooIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/doobox': typeof DooboxRoute
  '/login': typeof LoginRoute
  '/requests': typeof RequestsRoute
  '/doo/$id': typeof DooIdRoute
  '/doo': typeof DooIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/doo': typeof DooRouteWithChildren
  '/doobox': typeof DooboxRoute
  '/login': typeof LoginRoute
  '/requests': typeof RequestsRoute
  '/doo/$id': typeof DooIdRoute
  '/doo/': typeof DooIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/doo'
    | '/doobox'
    | '/login'
    | '/requests'
    | '/doo/$id'
    | '/doo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/doobox'
    | '/login'
    | '/requests'
    | '/doo/$id'
    | '/doo'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/doo'
    | '/doobox'
    | '/login'
    | '/requests'
    | '/doo/$id'
    | '/doo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DooRoute: typeof DooRouteWithChildren
  DooboxRoute: typeof DooboxRoute
  LoginRoute: typeof LoginRoute
  RequestsRoute: typeof RequestsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doobox': {
      id: '/doobox'
      path: '/doobox'
      fullPath: '/doobox'
      preLoaderRoute: typeof DooboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doo': {
      id: '/doo'
      path: '/doo'
      fullPath: '/doo'
      preLoaderRoute: typeof DooRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doo/': {
      id: '/doo/'
      path: '/'
      fullPath: '/doo/'
      preLoaderRoute: typeof DooIndexRouteImport
      parentRoute: typeof DooRoute
    }
    '/doo/$id': {
      id: '/doo/$id'
      path: '/$id'
      fullPath: '/doo/$id'
      preLoaderRoute: typeof DooIdRouteImport
      parentRoute: typeof DooRoute
    }
  }
}

interface DooRouteChildren {
  DooIdRoute: typeof DooIdRoute
  DooIndexRoute: typeof DooIndexRoute
}

const DooRouteChildren: DooRouteChildren = {
  DooIdRoute: DooIdRoute,
  DooIndexRoute: DooIndexRoute,
}

const DooRouteWithChildren = DooRoute._addFileChildren(DooRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DooRoute: DooRouteWithChildren,
  DooboxRoute: DooboxRoute,
  LoginRoute: LoginRoute,
  RequestsRoute: RequestsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
