export const API_ERROR_CODE = {
  LIMIT_EXCEEDED: "LIMIT_EXCEEDED",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  UNKNOWN: "UNKNOWN",
  SERVER_ERROR: "SERVER_ERROR",
  BAD_REQUEST: "BAD_REQUEST",
  CONFLICT: "CONFLICT",
  RUNTIME_ERROR: "RUNTIME_ERROR",
  TRANSPILATION_ERROR: "TRANSPILATION_ERROR",
} as const;
